#!/bin/bash
separator_block_width=18
markup=pango

[spotify]
command=$HOME/.config/i3/spotify_blocklet
interval=1
#color=#119966
color=#2f343f

#[weekend]
#label=
#command= SECS=$(( $(date --date="Fri. 17:30" +%s) - $(date +%s) )) && printf '%dd %dh %dm\n' $(($SECS/86400)) $(($SECS%86400/3600)) $(($SECS%3600/60))
#interval=15
#color=#2AA1AE
#119966
#color=#2f343f


#[bluetooth]
#interval=60
#signal=6

#[brightness]
#interval=60
#signal=2

[disk-root]
label=
command=~/.config/i3/i3blocks/disk /
interval=30
#color=#2AA1AE
color=#2f343f


[memory]
label=
command=~/.config/i3/i3blocks/memory
interval=15
#color=#2AA1AE
color=#2f343f


[cpu]
label=
command=~/.config/i3/i3blocks/cpu_usage
interval=5
#color=#2AA1AE
color=#2f343f

#[load]
#label=
#command=~/.config/i3/i3blocks/load_average
#interval=5
#color=#2AA1AE
#color=#2f343f

#[redshift]
#interval=120


[volume]
label=☊
command=~/.config/i3/i3blocks/volume
interval=2
signal=10
#color=#2AA1AE
color=#2f343f


[battery]
label=
command=~/.config/i3/i3blocks/battery BAT0
interval=30
#color=#2AA1AE
color=#2f343f


[time]
label=
#command=date '+%H:%M      %d-%m-%Y '
#command=date '+%H:%M   ⊲ '
command=date '+%H:%M  ⏐ '
interval=1
#color=#2AA1AE
color=#2f343f
